### ISSUE TITLE
Parse Json Array with Kotlin

### ISSUE THREAD

**Issue by mandy8055** [steelkiwi/Getting-started-with-Kotlin#1]
I am still having problems(I am a tyro in kotlin) in switching to kotlin but because of its numerous advantage; I was trying to parse Json array in Kotlin by the help of this project.This repository is very helpful to me  but there is only one regarding it that the result is always an empty list when parsing json array. I am trying to parse the json array like:

       [
	    {
	          "ID":1,
                "TITLE":"UPDATE 1-ECB to reveal bad loan hurdles for euro zone bank test -sources",
                "URL":"http://in.reuters.com/article/2014/03/10/eurozone-bank-tests-idINL6N0M70XH20140310",
                 "PUBLISHER":"Reuters",
                  "CATEGORY":"b",
                  "HOSTNAME":"in.reuters.com",
                  "TIMESTAMP":1394470505314	      },
   
	      {
		   
                  "ID":32,
                   "TITLE":"ECB to reveal bad loan hurdles for euro zone bank test - sources",
                    "URL":"http://www.euronews.com/business-newswires/2393252-ecb-to-reveal-bad-loan-hurdles-for-euro-zone-bank-test-sources/",
                    "PUBLISHER":"euronews",
                     "CATEGORY":"b",
                     "HOSTNAME":"www.euronews.com",
                    "TIMESTAMP":1394470505541
	       },
	
         ] 
I was able to achieve this result in java but failing in Kotlin. What are the things that I need to change in the code to achieve this type of parsing.Please help

**Comment by jvidalorozco1995** [comment]
@GET("/api/method/")
 fun getExamples(): Observable<List<Example>>

class Example 
{
@SerializedName("ID")
    @Expose
    var id: Int? = null
    @SerializedName("TITLE")
    @Expose
    var title: String? = null
    @SerializedName("URL")
    @Expose
    var url: String? = null
    @SerializedName("PUBLISHER")
    @Expose
    var publisher: String? = null
    @SerializedName("CATEGORY")
    @Expose
    var category: String? = null
    @SerializedName("HOSTNAME")
    @Expose
    var hostname: String? = null
    @SerializedName("TIMESTAMP")
    @Expose
    var timestamp: Int? = null
}

And permission internet
<uses-permission android:name="android.permission.INTERNET" />

**Comment by mandy8055** [comment]
Thank you Sir but I have done this and when I am trying to implement `Observable<List>` in `NewsApiInterface` it is raising error(`No type argument expected for Observable class` ) an because of which I am also encountering error in **NewsPresenter.kt** `loadNews()` method. Also,Is there a need of **Pagination.kt** and **NewsResponse.java** in the aforementioned parsing issue?
